name: CI for develop branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Construct version number
        id: version
        run: echo "::set-output name=version::$(date +'%Y%m%d').${GITHUB_RUN_NUMBER}"
        env:
          TZ: Asia/Tokyo

      - name: Print version number
        run: echo ${{ steps.version.outputs.version }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Maven Build
        run: mvn --batch-mode --update-snapshots verify
