name: CI for develop branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Mvn test with coverage
        run: >
          mvn --batch-mode --no-transfer-progress --update-snapshots org.jacoco:jacoco-maven-plugin:0.8.7:prepare-agent test org.jacoco:jacoco-maven-plugin:0.8.7:report

      - name: Generate JaCoCo badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Embed coverage result in README.md
        run: >
          sed -i -re "s,^\[!\[Coverage.*$,[![Coverage: ${{ steps.jacoco.outputs.coverage }}](.github/badges/jacoco.svg)](https://github.com/TRAdEWORKS/kafka-reverse-consumer/actions/runs/${GITHUB_RUN_ID}#artifacts)," README.md

      - name: Commit and push coverage result
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git commit README.md .github/badges -m "update coverage result ${{ steps.jacoco.outputs.coverage }})"
          git push

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/jacoco
