name: CI for main branch

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List GPG keys 1
        run: gpg --list-signatures --keyid-format 0xshort

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: List GPG keys 2
        run: gpg --list-signatures --keyid-format 0xshort

      - name: cat ~/.m2/settings.xml
        run: cat settings.xml

#      - name: Construct version number
#        id: version
#        run: echo "::set-output name=version::$(date +'%Y%m%d').${GITHUB_RUN_NUMBER}"
#        env:
#          TZ: Asia/Tokyo
#
#      - name: Set Maven version
#        run: mvn --batch-mode --no-transfer-progress versions:set -DnewVersion=${{ steps.version.outputs.version }}
#
#      - name: Publish package
#        run: mvn -X --batch-mode --no-transfer-progress deploy
#
#      - name: git tag
#        run: git tag "$(build.buildNumber)"
#
#      - name: git push --tags
#        run: git push --tags
